// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_YOZvfbgdyaeSBv5CfQPvU7B8Ls9ysHM',
    appId: '1:182480778477:web:88b1858d50ddf5214a08e4',
    messagingSenderId: '182480778477',
    projectId: 'eventee-2003',
    authDomain: 'eventee-2003.firebaseapp.com',
    storageBucket: 'eventee-2003.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDOTWodeOIBEPkasJyjlB8IzGhWT_7qms',
    appId: '1:182480778477:android:baba956f67d265c64a08e4',
    messagingSenderId: '182480778477',
    projectId: 'eventee-2003',
    storageBucket: 'eventee-2003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqDrd7aJHZHXUqDhcMrGWzoyNgRRmqNIk',
    appId: '1:182480778477:ios:be801be00b1870a64a08e4',
    messagingSenderId: '182480778477',
    projectId: 'eventee-2003',
    storageBucket: 'eventee-2003.firebasestorage.app',
    iosBundleId: 'com.example.eventee',
  );
}
